# Generated by Django 4.2.13 on 2024-06-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
